const actionTypes = {

  LANDING_PAGE_DATA_START: 'LANDING_PAGE_DATA_START',
  LANDING_PAGE_DATA_SUCCEEDED: 'LANDING_PAGE_DATA_SUCCEEDED',
  LANDING_PAGE_DATA_FAILED: 'LANDING_PAGE_DATA_FAILED',
}
export default actionTypes;